---
driver:
  name: docker
  use_sudo: false
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  privileged: true
  provision_command:
    - curl -sSL https://get.docker.com/ | sh



provisioner:
  name: shell
  data_path: .
  script: test/fixtures/bootstrap.sh
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>

# verifier:
#   ruby_bindir: <%= ENV['MY_RUBY_HOME'] || '/opt/sensu/embedded' %>/bin
verifier:
  ruby_bindir: /usr/local/bin

platforms:
  - name: debian-8

suites:
  - name: ruby-20
    driver:
      image: ruby:2.0-slim
  - name: ruby-21
    driver:
      image: ruby:2.1-slim
  - name: ruby-22
    driver:
      image: ruby:2.2-slim
  - name: ruby-230
    driver:
      image: ruby:2.3.0-slim
  - name: ruby-241
    driver:
      image: ruby:2.4.1-slim
