language: ruby
cache:
  - bundler
before_install:
  - gem install bundler -v 2.1
install:
  - bundle install
rvm:
  - 2.3.0
  - 2.4.1
notifications:
  email:
    recipients:
      - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
  - bundle exec rake quick
  #- bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
  - gem build sensu-plugins-docker.gemspec
  - gem install sensu-plugins-docker-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: Xx+9z5uHC/rDjklTV7nSE8+7SxDh+/EzE3dt1QjutCtMYM7DK+gtleffv+irF02nUc5wbOCn61xnaLhqljyYdSbtOSXqURRQGkQF9eg/IVMaHMVZHQ6SHktrKkUyX3ZW39WKgBiKaSGs/Z9ulCWp13q1GToCEABLZTX6SDqCiyU=
  gem: sensu-plugins-docker
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-docker
